name: Spec
on:
  push:
    branches: [master]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Run specs
        run: crystal spec -v .
